.START_TIME <- Sys.time()
devtools::load_all()
source(here::here("main/requirements.R"))
source(here::here("main/dependencies.R"))
message(paste0("Finished loading in ", round(Sys.time() - .START_TIME, 2)))
